name: BUILD.PULL-REQUESTS.BACKEND

on:
  workflow_call:
    inputs:
      java_varsion:
        default: '17'
        type: string

jobs:
  BUILD:

    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: BUILD
        run: |
          pwd && ls -al
          cd service
          pwd && ls -al
          chmod +x gradlew
          ./gradlew build
