name: BUILD.PULL-REQUESTS

on:
  pull_request:

jobs:
  SERVICE:
    uses: YuliiaLysak/testcontainers-cosmos-db/.github/workflows/build-pull-requests-backend.yml@master
    with:
      java_version: '17'
    secrets: inherit
